sonar.projectKey=ifs24050-pabwe2026-sk-p5-nuxt
sonar.projectName=Delcom Cash Flow Nuxt
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.vue
sonar.exclusions=**/*.test.ts,**/*.test.vue,**/node_modules/**,**/.nuxt/**,**/.output/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
