<script setup lang="ts">
import { onMounted } from 'vue'
import { ArrowLeft, Pencil, Trash2 } from 'lucide-vue-next'
import { useCashFlowsStore } from '../states/cashFlowsStore'
import { formatDateTime, formatRupiah, showConfirmDialog, showErrorDialog } from '~/helpers/toolsHelper'
const route = useRoute(); const store = useCashFlowsStore()
onMounted(async () => { try { await store.fetchCashFlow(String(route.params.cashFlowId)) } catch(e) { await showErrorDialog('Gagal memuat transaksi', e instanceof Error ? e.message : '') } })
async function remove() { const c = await showConfirmDialog('Hapus transaksi?', 'Data ini akan dihapus permanen.'); if (c.isConfirmed && store.cashFlow) { try { await store.removeCashFlow(store.cashFlow.id); await navigateTo('/') } catch(e) { await showErrorDialog('Gagal menghapus', e instanceof Error ? e.message : '') } } }
</script>
<template><div class="mx-auto max-w-3xl"><NuxtLink to="/" class="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-indigo-700"><ArrowLeft :size="16"/> Kembali ke dashboard</NuxtLink><div v-if="store.cashFlow" class="mt-6 overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div class="bg-indigo-700 p-7 text-white"><p class="text-sm font-semibold text-indigo-200">DETAIL TRANSAKSI</p><h1 class="mt-2 text-2xl font-extrabold">{{ store.cashFlow.label }}</h1><p class="mt-4 text-3xl font-extrabold">{{ store.cashFlow.type==='inflow'?'+':'−' }}{{ formatRupiah(store.cashFlow.nominal) }}</p><span class="mt-3 inline-flex rounded-full px-3 py-1 text-xs font-bold" :class="store.cashFlow.type==='inflow'?'bg-emerald-400/20 text-emerald-100':'bg-rose-400/20 text-rose-100'">{{ store.cashFlow.type==='inflow'?'Pemasukan / Inflow':'Pengeluaran / Outflow' }}</span></div><div class="grid gap-6 p-7 sm:grid-cols-2"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-600">Sumber dana</p><p class="mt-2 font-bold">{{ store.cashFlow.source==='cash'?'Tunai':store.cashFlow.source==='savings'?'Tabungan':'Pinjaman' }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-600">Kategori</p><p class="mt-2 font-bold">{{ store.cashFlow.label }}</p></div><div class="sm:col-span-2"><p class="text-xs font-bold uppercase tracking-wider text-slate-600">Deskripsi</p><p class="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{{ store.cashFlow.description || 'Tidak ada deskripsi.' }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-600">Dibuat pada</p><p class="mt-2 text-sm font-semibold">{{ formatDateTime(store.cashFlow.created_at) }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-600">Diperbarui pada</p><p class="mt-2 text-sm font-semibold">{{ formatDateTime(store.cashFlow.updated_at) }}</p></div></div><div class="flex justify-end gap-3 border-t border-slate-100 p-5"><button @click="remove" class="inline-flex items-center gap-2 rounded-xl border border-rose-200 px-4 py-2.5 text-sm font-bold text-rose-700"><Trash2 :size="16"/> Hapus</button><NuxtLink to="/" class="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white"><Pencil :size="16"/> Kembali untuk mengubah</NuxtLink></div></div><div v-else class="mt-8 rounded-2xl bg-white p-12 text-center text-slate-600">Memuat detail transaksi...</div></div></template>
