<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { ArrowDownLeft, ArrowUpRight, Wallet, Plus, Trash2, Search, Eye, Pencil, RefreshCw } from 'lucide-vue-next'
import { useCashFlowsStore } from '../states/cashFlowsStore'
import { formatDate, formatRupiah, showConfirmDialog, showErrorDialog, showSuccessDialog } from '~/helpers/toolsHelper'
import type { CashFlow, CashFlowQueryParams } from '../api/cashFlowApi'
const store = useCashFlowsStore()
const filters = ref<CashFlowQueryParams>({ type: '', source: '', label: '', start_date: '', end_date: '' })
const search = ref(''); const showAdd = ref(false); const editing = ref<CashFlow | null>(null)
const form = ref({ type: 'inflow' as 'inflow'|'outflow', source: 'cash' as 'cash'|'savings'|'loans', label: '', nominal: 0, description: '' })
const rows = computed(() => store.cashFlows.filter(x => `${x.label} ${x.description || ''}`.toLowerCase().includes(search.value.toLowerCase())))
const totalIn = computed(() => store.stats.total_inflow || store.cashFlows.filter(x => x.type === 'inflow').reduce((a,x) => a + Number(x.nominal), 0))
const totalOut = computed(() => store.stats.total_outflow || store.cashFlows.filter(x => x.type === 'outflow').reduce((a,x) => a + Number(x.nominal), 0))
const metrics = computed(() => [
 { label: 'Saldo kas bersih', value: formatRupiah(totalIn.value-totalOut.value), icon: Wallet, tone: 'indigo' },
 { label: 'Total pemasukan', value: formatRupiah(totalIn.value), icon: ArrowDownLeft, tone: 'green' },
 { label: 'Total pengeluaran', value: formatRupiah(totalOut.value), icon: ArrowUpRight, tone: 'red' },
 { label: 'Saldo tunai', value: formatRupiah(store.stats.cash), icon: Wallet, tone: 'blue' },
 { label: 'Saldo tabungan', value: formatRupiah(store.stats.savings), icon: Wallet, tone: 'violet' },
 { label: 'Saldo pinjaman', value: formatRupiah(store.stats.loans), icon: Wallet, tone: 'amber' }
])
async function load() { try { await store.fetchCashFlows(filters.value); await store.fetchLabels() } catch (e) { await showErrorDialog('Gagal memuat data', e instanceof Error ? e.message : '') } }
watch(filters, () => { void load() }, { deep: true })
onMounted(load)
function openEdit(item: CashFlow) { editing.value = item; form.value = { type: item.type, source: item.source, label: item.label, nominal: item.nominal, description: item.description || '' }; showAdd.value = true }
function resetForm() { editing.value = null; form.value = { type: 'inflow', source: 'cash', label: '', nominal: 0, description: '' } }
async function save() { try { if (editing.value) await store.changeCashFlow(editing.value.id, form.value); else await store.addCashFlow(form.value); showAdd.value = false; resetForm(); await showSuccessDialog('Berhasil', 'Transaksi berhasil disimpan.') } catch (e) { await showErrorDialog('Gagal menyimpan', e instanceof Error ? e.message : '') } }
async function remove(id: CashFlow['id']) { const result = await showConfirmDialog('Hapus transaksi?', 'Transaksi yang dihapus tidak dapat dipulihkan.'); if (result.isConfirmed) { try { await store.removeCashFlow(id); await showSuccessDialog('Terhapus', 'Transaksi berhasil dihapus.') } catch(e) { await showErrorDialog('Gagal menghapus', e instanceof Error ? e.message : '') } } }
async function clearAll() { const result = await showConfirmDialog('Reset semua transaksi?', 'Semua catatan arus kas akan dihapus permanen.'); if (result.isConfirmed) { try { await store.removeAllCashFlows(); await showSuccessDialog('Selesai', 'Semua transaksi telah dihapus.') } catch(e) { await showErrorDialog('Gagal reset', e instanceof Error ? e.message : '') } } }
</script>
<template>
  <div class="space-y-7">
    <section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-bold text-indigo-600">DASHBOARD FINANSIAL</p><h1 class="mt-2 text-3xl font-extrabold tracking-tight">Ringkasan arus kas</h1><p class="mt-2 text-sm text-slate-600">Pantau uang masuk dan keluar, semuanya dalam satu tempat.</p></div><div class="flex flex-wrap gap-2"><button @click="clearAll" class="inline-flex items-center gap-2 rounded-xl border border-red-200 bg-white px-4 py-3 text-sm font-bold text-red-700 hover:bg-red-50"><Trash2 :size="16"/> Reset data</button><button @click="resetForm();showAdd=true" class="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-indigo-200 hover:bg-indigo-700"><Plus :size="17"/> Tambah transaksi</button></div></section>
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><article v-for="m in metrics" :key="m.label" class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><p class="text-sm font-semibold text-slate-600">{{ m.label }}</p><span class="grid h-10 w-10 place-items-center rounded-xl" :class="{'bg-indigo-50 text-indigo-700':m.tone==='indigo','bg-emerald-50 text-emerald-700':m.tone==='green','bg-rose-50 text-rose-700':m.tone==='red','bg-blue-50 text-blue-600':m.tone==='blue','bg-violet-50 text-violet-600':m.tone==='violet','bg-amber-50 text-amber-800':m.tone==='amber'}"><component :is="m.icon" :size="19"/></span></div><p class="mt-4 text-2xl font-extrabold tracking-tight">{{ m.value }}</p></article></section>
    <section class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm md:p-6"><div class="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="text-lg font-extrabold">Riwayat transaksi</h2><p class="mt-1 text-sm text-slate-600">Cari, filter, dan kelola catatanmu.</p></div><button @click="load" class="inline-flex items-center gap-2 self-start rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold"><RefreshCw :size="15"/> Muat ulang</button></div>
      <div class="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><label class="relative xl:col-span-2"><Search class="absolute left-3 top-3 text-slate-600" :size="16"/><input v-model="search" class="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-indigo-500" placeholder="Cari transaksi..."/></label><select v-model="filters.type" class="filter"><option value="">Semua jenis</option><option value="inflow">Pemasukan</option><option value="outflow">Pengeluaran</option></select><select v-model="filters.source" class="filter"><option value="">Semua sumber</option><option value="cash">Tunai</option><option value="savings">Tabungan</option><option value="loans">Pinjaman</option></select><select v-model="filters.label" class="filter"><option value="">Semua label</option><option v-for="label in store.labels" :key="label" :value="label">{{ label }}</option></select><div class="flex gap-2"><input v-model="filters.start_date" type="date" aria-label="Tanggal awal" class="filter min-w-0"/><input v-model="filters.end_date" type="date" aria-label="Tanggal akhir" class="filter min-w-0"/></div></div>
      <div v-if="store.isLoading" class="py-16 text-center text-sm text-slate-600">Memuat transaksi...</div><div v-else-if="!rows.length" class="rounded-xl border border-dashed border-slate-200 py-16 text-center"><div class="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><Wallet :size="22"/></div><p class="mt-4 font-bold">Belum ada transaksi</p><p class="mt-1 text-sm text-slate-600">Tambahkan transaksi pertamamu untuk mulai mencatat.</p><button @click="resetForm();showAdd=true" class="mt-4 text-sm font-bold text-indigo-700">+ Tambah transaksi</button></div>
      <div v-else class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead><tr class="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-600"><th class="pb-3 pr-4">Kategori / keterangan</th><th class="pb-3 pr-4">Sumber</th><th class="pb-3 pr-4">Tanggal</th><th class="pb-3 pr-4">Nominal</th><th class="pb-3 text-right">Aksi</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id" class="border-b border-slate-50 last:border-0"><td class="py-4 pr-4"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl" :class="item.type==='inflow'?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'"><component :is="item.type==='inflow'?ArrowDownLeft:ArrowUpRight" :size="18"/></span><div><p class="font-bold">{{ item.label }}</p><p class="mt-1 max-w-xs truncate text-xs text-slate-600">{{ item.description || 'Tanpa keterangan' }}</p></div></div></td><td class="py-4 pr-4 capitalize text-slate-600">{{ item.source==='cash'?'Tunai':item.source==='savings'?'Tabungan':'Pinjaman' }}</td><td class="py-4 pr-4 text-slate-600">{{ formatDate(item.created_at) }}</td><td class="py-4 pr-4 font-extrabold" :class="item.type==='inflow'?'text-emerald-700':'text-rose-700'">{{ item.type==='inflow'?'+':'−' }}{{ formatRupiah(item.nominal) }}</td><td class="py-4 text-right"><div class="inline-flex gap-1"><NuxtLink :to="`/cash-flows/${item.id}`" aria-label="Lihat detail" class="rounded-lg p-2 text-slate-600 hover:bg-slate-100"><Eye :size="16"/></NuxtLink><button aria-label="Ubah transaksi" @click="openEdit(item)" class="rounded-lg p-2 text-indigo-600 hover:bg-indigo-50"><Pencil :size="16"/></button><button aria-label="Hapus transaksi" @click="remove(item.id)" class="rounded-lg p-2 text-rose-700 hover:bg-rose-50"><Trash2 :size="16"/></button></div></td></tr></tbody></table></div>
    </section>
    <div v-if="showAdd" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" @click.self="showAdd=false"><section class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div class="flex items-center justify-between"><h2 class="text-xl font-extrabold">{{ editing ? 'Ubah transaksi' : 'Tambah transaksi' }}</h2><button @click="showAdd=false" aria-label="Tutup modal" class="rounded-lg px-3 py-1 text-slate-600 hover:bg-slate-100">✕</button></div><form class="mt-5 space-y-4" @submit.prevent="save"><label class="block text-sm font-semibold">Jenis arus kas<select v-model="form.type" class="filter mt-2 w-full"><option value="inflow">Inflow / Pemasukan</option><option value="outflow">Outflow / Pengeluaran</option></select></label><label class="block text-sm font-semibold">Sumber dana<select v-model="form.source" class="filter mt-2 w-full"><option value="cash">Tunai</option><option value="savings">Tabungan</option><option value="loans">Pinjaman</option></select></label><label class="block text-sm font-semibold">Label kategori<input v-model.trim="form.label" required class="filter mt-2 w-full" placeholder="Contoh: Makanan"/></label><label class="block text-sm font-semibold">Nominal (Rp)<input v-model.number="form.nominal" required min="1" type="number" class="filter mt-2 w-full" placeholder="100000"/></label><label class="block text-sm font-semibold">Deskripsi<textarea v-model.trim="form.description" rows="3" class="filter mt-2 w-full" placeholder="Tambahkan keterangan..."/></label><div class="flex justify-end gap-2 pt-2"><button type="button" @click="showAdd=false" class="rounded-xl border border-slate-200 px-4 py-2.5 font-semibold">Batal</button><button class="rounded-xl bg-indigo-600 px-5 py-2.5 font-bold text-white">{{ editing?'Simpan perubahan':'Simpan transaksi' }}</button></div></form></section></div>
  </div>
</template>
<style scoped>.filter{border:1px solid #e2e8f0;border-radius:.75rem;background:white;padding:.65rem .75rem;font-size:.8rem;outline:none}.filter:focus{border-color:#6366f1;box-shadow:0 0 0 3px #e0e7ff}</style>
