import { defineStore } from 'pinia'
import { createCashFlowApi, deleteAllCashFlowsApi, deleteCashFlowApi, getCashFlowApi, getCashFlowLabelsApi, getCashFlowsApi, getDailyStatsApi, getMonthlyStatsApi, updateCashFlowApi, type CashFlow, type CashFlowQueryParams, type CashFlowStats } from '../api/cashFlowApi'
const emptyStats = (): CashFlowStats => ({ total_inflow: 0, total_outflow: 0, cash: 0, savings: 0, loans: 0 })
export interface CashFlowsState { cashFlows: CashFlow[]; cashFlow: CashFlow | null; stats: CashFlowStats; labels: string[]; dailyStats: unknown; monthlyStats: unknown; isLoading: boolean; error: string; isCashFlowAdd: boolean; isCashFlowAdded: boolean; isCashFlowChange: boolean; isCashFlowChanged: boolean; isCashFlowDelete: boolean; isCashFlowDeleted: boolean; isCashFlowDeleteAll: boolean; isCashFlowDeletedAll: boolean }
export const useCashFlowsStore = defineStore('cashFlows', {
  state: (): CashFlowsState => ({ cashFlows: [], cashFlow: null, stats: emptyStats(), labels: [], dailyStats: null, monthlyStats: null, isLoading: false, error: '', isCashFlowAdd: false, isCashFlowAdded: false, isCashFlowChange: false, isCashFlowChanged: false, isCashFlowDelete: false, isCashFlowDeleted: false, isCashFlowDeleteAll: false, isCashFlowDeletedAll: false }),
  actions: {
    async fetchCashFlows(params: CashFlowQueryParams = {}) { this.isLoading = true; this.error = ''; try { const r = await getCashFlowsApi(params); this.cashFlows = r.data?.cash_flows || r.data?.cashFlows || r.data || r.cash_flows || []; const s = r.data?.stats || r.stats; if (s) { this.stats = { ...emptyStats(), ...s } } return this.cashFlows } catch (e) { this.error = e instanceof Error ? e.message : 'Gagal memuat arus kas'; throw e } finally { this.isLoading = false } },
    async fetchCashFlow(id: number | string) { const r = await getCashFlowApi(id); this.cashFlow = r.data?.cash_flow || r.data || r.cash_flow || r; return this.cashFlow },
    async fetchLabels() { const r = await getCashFlowLabelsApi(); this.labels = r.data?.labels || r.data || r.labels || []; return this.labels },
    async fetchStats() { const [daily, monthly] = await Promise.all([getDailyStatsApi(), getMonthlyStatsApi()]); this.dailyStats = daily.data || daily; this.monthlyStats = monthly.data || monthly; return { daily: this.dailyStats, monthly: this.monthlyStats } },
    async addCashFlow(payload: Omit<CashFlow, 'id' | 'created_at' | 'updated_at'>) { this.isCashFlowAdd = true; this.isCashFlowAdded = false; try { await createCashFlowApi(payload); this.isCashFlowAdded = true; await this.fetchCashFlows(); } finally { this.isCashFlowAdd = false } },
    async changeCashFlow(id: number | string, payload: Partial<Omit<CashFlow, 'id'>>) { this.isCashFlowChange = true; this.isCashFlowChanged = false; try { await updateCashFlowApi(id, payload); this.isCashFlowChanged = true; await this.fetchCashFlows(); } finally { this.isCashFlowChange = false } },
    async removeCashFlow(id: number | string) { this.isCashFlowDelete = true; this.isCashFlowDeleted = false; try { await deleteCashFlowApi(id); this.isCashFlowDeleted = true; this.cashFlows = this.cashFlows.filter(x => String(x.id) !== String(id)) } finally { this.isCashFlowDelete = false } },
    async removeAllCashFlows() { this.isCashFlowDeleteAll = true; this.isCashFlowDeletedAll = false; try { await deleteAllCashFlowsApi(); this.cashFlows = []; this.stats = emptyStats(); this.isCashFlowDeletedAll = true } finally { this.isCashFlowDeleteAll = false } }
  }
})
