<script setup lang="ts">
import { ref } from 'vue'
import { useAuthStore } from '../states/authStore'
import { showErrorDialog, showSuccessDialog } from '~/helpers/toolsHelper'
const auth = useAuthStore(); const name = ref(''); const email = ref(''); const password = ref('')
async function submit() { try { await auth.register({ name: name.value, email: email.value, password: password.value }); await showSuccessDialog('Registrasi berhasil', 'Silakan masuk menggunakan akun yang dibuat.'); await navigateTo('/auth/login') } catch (e) { await showErrorDialog('Registrasi gagal', e instanceof Error ? e.message : 'Silakan coba lagi') } }
</script>
<template><div><p class="text-sm font-bold uppercase tracking-widest text-indigo-600">Mulai sekarang</p><h2 class="mt-2 text-3xl font-extrabold">Buat akun baru</h2><p class="mt-2 text-sm text-slate-500">Hanya butuh beberapa detail untuk memulai.</p><form class="mt-8 space-y-4" @submit.prevent="submit"><label class="block text-sm font-semibold">Nama lengkap<input v-model.trim="name" required class="field" placeholder="Nama lengkap" /></label><label class="block text-sm font-semibold">Email<input v-model.trim="email" type="email" required autocomplete="email" class="field" placeholder="nama@email.com" /></label><label class="block text-sm font-semibold">Password<input v-model="password" required minlength="6" type="password" class="field" placeholder="Minimal 6 karakter" /></label><button :disabled="auth.isLoading" class="w-full rounded-xl bg-indigo-600 px-4 py-3 font-bold text-white hover:bg-indigo-700">{{ auth.isLoading ? 'Memproses...' : 'Buat akun' }}</button></form><p class="mt-6 text-center text-sm text-slate-500">Sudah punya akun? <NuxtLink class="font-bold text-indigo-700" to="/auth/login">Masuk</NuxtLink></p></div></template>
<style scoped>.field{display:block;width:100%;margin-top:.5rem;border:1px solid #e2e8f0;border-radius:.75rem;padding:.75rem 1rem;outline:none}.field:focus{border-color:#6366f1;box-shadow:0 0 0 4px #e0e7ff}</style>
