<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Camera, Save, ShieldCheck, UserRound } from 'lucide-vue-next'
import { useUsersStore } from '../states/usersStore'
import { showErrorDialog, showSuccessDialog } from '~/helpers/toolsHelper'
const store = useUsersStore(); const bio = ref(''); const oldPassword = ref(''); const newPassword = ref(''); const avatar = ref<File | null>(null)
onMounted(async () => { try { const p = await store.fetchProfile(); bio.value = p?.bio || '' } catch(e) { await showErrorDialog('Gagal memuat profil', e instanceof Error ? e.message : '') } })
async function saveBio() { try { await store.updateBio(bio.value); await showSuccessDialog('Profil diperbarui', 'Bio berhasil disimpan.') } catch(e) { await showErrorDialog('Gagal menyimpan', e instanceof Error ? e.message : '') } }
async function savePassword() { try { await store.updatePassword(oldPassword.value, newPassword.value); oldPassword.value=''; newPassword.value=''; await showSuccessDialog('Password diubah', 'Password berhasil diperbarui.') } catch(e) { await showErrorDialog('Gagal mengubah password', e instanceof Error ? e.message : '') } }
async function uploadPhoto() { if (!avatar.value) { return } try { await store.uploadAvatar(avatar.value); await showSuccessDialog('Foto diunggah', 'Foto profil berhasil dikirim.') } catch(e) { await showErrorDialog('Gagal mengunggah foto', e instanceof Error ? e.message : '') } }
</script>
<template><div class="mx-auto max-w-3xl"><p class="text-sm font-bold text-indigo-600">PENGATURAN AKUN</p><h1 class="mt-2 text-3xl font-extrabold">Profil saya</h1><p class="mt-2 text-sm text-slate-600">Perbarui informasi dan keamanan akunmu.</p><section class="mt-7 rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div class="flex items-center gap-4 border-b border-slate-100 pb-6"><div class="grid h-16 w-16 place-items-center rounded-2xl bg-indigo-100 text-indigo-700"><UserRound :size="28"/></div><div><h2 class="text-lg font-extrabold">{{ store.profile?.name || store.profile?.username || 'Profil pengguna' }}</h2><p class="text-sm text-slate-600">{{ store.profile?.email || 'Email tidak tersedia' }}</p><p class="mt-1 text-xs text-slate-600">Informasi akun</p></div></div><form class="space-y-4 py-6" @submit.prevent="saveBio"><h3 class="font-extrabold">Informasi pribadi</h3><label class="block text-sm font-semibold">Bio<textarea v-model="bio" rows="4" maxlength="500" class="mt-2 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-indigo-500" placeholder="Ceritakan sedikit tentang dirimu..."/></label><button class="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white"><Save :size="16"/> Simpan bio</button></form><div class="border-t border-slate-100 py-6"><h3 class="font-extrabold">Foto profil</h3><div class="mt-3 flex flex-wrap items-center gap-3"><input type="file" accept="image/*" @change="avatar=($event.target as HTMLInputElement).files?.[0] || null" class="max-w-full text-sm"/><button @click="uploadPhoto" class="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold"><Camera :size="16"/> Unggah foto</button></div></div><form class="space-y-4 border-t border-slate-100 pt-6" @submit.prevent="savePassword"><h3 class="flex items-center gap-2 font-extrabold"><ShieldCheck :size="18"/> Keamanan akun</h3><label class="block text-sm font-semibold">Password saat ini<input v-model="oldPassword" type="password" required class="mt-2 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-indigo-500"/></label><label class="block text-sm font-semibold">Password baru<input v-model="newPassword" type="password" required minlength="6" class="mt-2 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-indigo-500"/></label><button class="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Ubah password</button></form></section></div></template>
